version: '3.8'

services:

  php:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: php
    volumes:
        - vendor:/app/vendor
        - .:/app
    ports:
      - 8090:8000
  front:
    build:
        context: .
        dockerfile: DockerfileFront
    container_name: front
    volumes:
        - node_modules:/app/node_modules
        - .:/app
    ports:
      - 5173:5173
  db:
    image: postgres
    restart: always
    ports:
      - 15433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456

volumes:
  pgdata:
  vendor:
  node_modules: